terminals = [
    # Buenos Aires / CABA
    "Terminal Retiro",
    "Terminal Dellepiane",
    "Terminal La Plata",
    "Terminal Mar del Plata",
    "Terminal Bahía Blanca",
    "Terminal Tandil",
    "Terminal Olavarría",
    "Terminal Pergamino",
    "Terminal Junín",
    "Terminal San Nicolás",
    "Terminal Necochea",
    "Terminal Azul",
    "Terminal Chivilcoy",
    "Terminal Tres Arroyos",
    "Terminal Villa Gesell",
    "Terminal Pinamar",
    "Terminal San Clemente del Tuyú",
    # Entre Ríos
    "Terminal Paraná",
    "Terminal Concepción del Uruguay",
    "Terminal Gualeguaychú",
    "Terminal Concordia",
    "Terminal Colón",
    "Terminal Gualeguay",
    "Terminal Victoria",
    "Terminal Villaguay",
    "Terminal Federación",
    "Terminal Chajarí",
    "Terminal La Paz",
    "Terminal Diamante",
    "Terminal Nogoyá",
    # Santa Fe
    "Terminal Rosario",
    "Terminal Santa Fe",
    "Terminal Rafaela",
    "Terminal Venado Tuerto",
    "Terminal Reconquista",
    # Córdoba
    "Terminal Córdoba",
    "Terminal Río Cuarto",
    "Terminal Villa María",
    "Terminal Villa Carlos Paz",
    "Terminal San Francisco",
    # Cuyo
    "Terminal Mendoza",
    "Terminal San Rafael",
    "Terminal San Juan",
    "Terminal San Luis",
    "Terminal Villa Mercedes",
    # NOA
    "Terminal Tucumán",
    "Terminal Salta",
    "Terminal San Salvador de Jujuy",
    "Terminal Santiago del Estero",
    "Terminal Termas de Río Hondo",
    "Terminal Catamarca",
    "Terminal La Rioja",
    # NEA
    "Terminal Corrientes",
    "Terminal Paso de los Libres",
    "Terminal Resistencia",
    "Terminal Formosa",
    "Terminal Posadas",
    "Terminal Puerto Iguazú",
    "Terminal Oberá",
    # La Pampa
    "Terminal Santa Rosa",
    # Patagonia
    "Terminal Neuquén",
    "Terminal San Martín de los Andes",
    "Terminal Bariloche",
    "Terminal Viedma",
    "Terminal General Roca",
    "Terminal Puerto Madryn",
    "Terminal Trelew",
    "Terminal Comodoro Rivadavia",
    "Terminal Esquel",
    "Terminal Río Gallegos",
    "Terminal El Calafate",
    "Terminal Río Grande",
    "Terminal Ushuaia",
]
